### ISSUE TITLE
Camera near < 1 noise is serious

### ISSUE THREAD

**Issue by iDerekLi** [Fyrestar/THREE.InfiniteGridHelper#2]
Camera near < 1 noise is serious

```javascript
// good
const camera = new THREE.PerspectiveCamera(80, window.innerWidth / window.innerHeight, 1, 8000);
```
![image](https://user-images.githubusercontent.com/24502299/110261806-a14b2d00-7fec-11eb-8c9f-96760c9ac810.png)

```javascript
// bad
const camera = new THREE.PerspectiveCamera(80, window.innerWidth / window.innerHeight, 0.1, 8000);
```
![image](https://user-images.githubusercontent.com/24502299/110261913-f25b2100-7fec-11eb-8931-41e152c5a32b.png)

**Comment by Fyrestar** [comment]
Can you demonstrate your issue with a live example? I used your parameters also with higher distance

![image](https://user-images.githubusercontent.com/28584767/110284737-7eb41680-7fe2-11eb-89e4-52ce7c44ddd5.png)

**Comment by iDerekLi** [comment]
https://codepen.io/iderekli/pen/LYbgpOJ

But I modified
  ~~`const geometry = new PlaneBufferGeometry(2, 2, 1, 1);`~~
  replace with
  `const geometry = new PlaneBufferGeometry(1, 1, 1, 1);`
  when near < 1, changing from 2 to 1 || 0.5 can achieve the goal

**Comment by Fyrestar** [comment]
> But I modified
const geometry = new PlaneBufferGeometry(2, 2, 1, 1);
replace with
const geometry = new PlaneBufferGeometry(1, 1, 1, 1);
when near < 1, changing from 2 to 1 || 0.5 can achieve the goal

I'm not sure what you mean, the pen also looks fine

![image](https://user-images.githubusercontent.com/28584767/110288127-d43ef200-7fe7-11eb-887c-3cf5ded5de74.png)

**Comment by Fyrestar** [comment]
Is your problem solved?

**Comment by iDerekLi** [comment]
Thank you very much, it has been resolved
