### ISSUE TITLE
How can I add glow to grid lines ?

### ISSUE THREAD

**Issue by Uttam-EWW** [Fyrestar/THREE.InfiniteGridHelper#7]
So I wants add glow to the grid lines. something like below.

![image](https://user-images.githubusercontent.com/86663119/153593664-8c7ff7ad-c5fa-47c4-bcff-29d1346c8155.png)

**Comment by Uttam-EWW** [comment]
Thank you for your response, could you please share me some links where I can get some reference for the same.

**Comment by TresAbhi** [comment]
https://discourse.threejs.org/t/solved-effectcomposer-layers/3158/4

**Comment by Uttam-EWW** [comment]
Thank you so much for your such quick response.
